---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: goldcar-alpakka-kafka-microservice
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: goldcar-alpakka-kafka-microservice
    spec:
      containers:
      - name: goldcar-alpakka-kafka-microservice
        image: goldcar-alpakka-kafka-microservice
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
# Still not ready, it is failing in Kubernetes with the message and need further studying
# Liveness probe failed: Get http://172.17.0.9:8080/health: dial tcp 172.17.0.9:8080: getsockopt: connection refused
#        livenessProbe:
#          initialDelaySeconds: 5
#          periodSeconds: 5
#          httpGet:
#            path: /health
#            port: 8080
#        resources:
#          limits:
#            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: goldcar-alpakka-kafka-microservice-service
spec:
  type: NodePort
  selector:
    app: goldcar-alpakka-kafka-microservice
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32000
