---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: goldcar-alpakka-kafka-microservice
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: goldcar-alpakka-kafka-microservice
    spec:
      containers:
      - name: goldcar-alpakka-kafka-microservice
        image: goldcar-alpakka-kafka-microservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: goldcar-alpakka-kafka-microservice-service
spec:
  type: NodePort
  selector:
    app: goldcar-alpakka-kafka-microservice
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32000

